// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhbllkbPs0oTlz1o-w0OexOfeCuw2Zb8',
    appId: '1:509767817518:web:01767a9009e62aebe582bf',
    messagingSenderId: '509767817518',
    projectId: 'hospital-virtuel',
    authDomain: 'hospital-virtuel.firebaseapp.com',
    storageBucket: 'hospital-virtuel.firebasestorage.app',
    measurementId: 'G-H9DWYZR78K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfNIjjob0t3DBJN5rlTdsTC7c9F3f5qEs',
    appId: '1:509767817518:android:7673cf416f5357cae582bf',
    messagingSenderId: '509767817518',
    projectId: 'hospital-virtuel',
    storageBucket: 'hospital-virtuel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoX319rcFHJ_n0opyUA9SYobsZQAI-Qq4',
    appId: '1:509767817518:ios:34fffc92c211e2bfe582bf',
    messagingSenderId: '509767817518',
    projectId: 'hospital-virtuel',
    storageBucket: 'hospital-virtuel.firebasestorage.app',
    iosBundleId: 'com.example.hospitalVirtuel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoX319rcFHJ_n0opyUA9SYobsZQAI-Qq4',
    appId: '1:509767817518:ios:34fffc92c211e2bfe582bf',
    messagingSenderId: '509767817518',
    projectId: 'hospital-virtuel',
    storageBucket: 'hospital-virtuel.firebasestorage.app',
    iosBundleId: 'com.example.hospitalVirtuel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMhbllkbPs0oTlz1o-w0OexOfeCuw2Zb8',
    appId: '1:509767817518:web:7d46aed4c063d5c2e582bf',
    messagingSenderId: '509767817518',
    projectId: 'hospital-virtuel',
    authDomain: 'hospital-virtuel.firebaseapp.com',
    storageBucket: 'hospital-virtuel.firebasestorage.app',
    measurementId: 'G-849DPJV2HD',
  );
}
